apiVersion: apps/v1 
kind: Deployment
metadata:
  name: api-mutante-deployment
spec:
  selector:
    matchLabels:
      app: mutantes
      role: web-api
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: mutantes
        role: web-api
        tier: backend
    spec:
      containers:
      - name: web-api
        image: asabaroni/mutantes:1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379

