apiVersion: apps/v1 
kind: Deployment
metadata:
  name: api-mutantes
spec:
  selector:
    matchLabels:
      app: mutantes
      role: slave
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: mutantes
        role: slave
        tier: backend
    spec:
      containers:
      - name: mutantes
        image: asabaroni/mutantes:1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access an environment variable to find the master
          # service's host, comment out the 'value: dns' line above, and
          # uncomment the line below:
          # value: env
        ports:
        - containerPort: 6379
---
