# kubetpl:syntax:go-template
---
apiVersion: apps/v1 
---
data:
   application.properties: |

      ##
      # Configuración ambiental para desarrollo (develop)
      ##
      
      # Base de datos
      spring.datasource.url=jdbc:sqlserver://localhost:1433;database=api_mutantes
      spring.datasource.username=sa
      spring.datasource.password=Pa$$w0rd1
      spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

      logging.level.org.springframework.web=INFO
      logging.level.org.springframework.ws.client.MessageTracing.sent=DEBUG
      logging.level.org.springframework.ws.server.MessageTracing.sent=DEBUG
      logging.level.org.springframework.ws.client.MessageTracing.received=TRACE
      logging.level.org.springframework.ws.server.MessageTracing.received=TRACE

      spring.flyway.enabled=true
      spring.flyway.baseline-on-migrate=true

kind: Deployment
metadata:
  name: api-mutantes
spec:
  selector:
    matchLabels:
      app: mutantes
      role: slave
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: mutantes
        role: slave
        tier: backend
    spec:
      containers:
      - name: mutantes
        image: asabaroni/mutantes:1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access an environment variable to find the master
          # service's host, comment out the 'value: dns' line above, and
          # uncomment the line below:
          # value: env
        ports:
        - containerPort: 6379

kind: ConfigMap
metadata:
   creationTimestamp: null
   name: {{ .APP_NAME }}-cm
   namespace: {{ .NAMESPACE_NAME }}